config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

resources :users do
  resources :posts do
    resources :comments
  end
end

  get '/feed', to: 'posts#feed'

  # leads home
  get '/' => 'users#index'
  get '/users' => 'user/#index'

  #leads to user account page
  get '/users' => 'users#show'

  #leads to posts
  get '/posts' => 'users#posts'

  #leads to account; where settings can be edited
  get '/account' => 'users#account'

  #creates new post
  post '/posts' => 'post#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  root 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email, :username, :password
  validates :password, confirmation: { message: "Passwords Do Not Match" }
  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

    def create
      @comment = @post.comments.create(params[:comment].permit(:content))
      @comment.user_id = current_user.id
      @comment.save

      if @comment.save
        redirect_back(fallback_location: root_path)
      else
        render 'new'
      end
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def feed
      @posts = Post.all
  end

  def current_user
    if session[:user_id]
        @current_user = User.find(session[:user_id])
    end
end

  def users
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

  end

  def posts
      @user = User.find(params[:id])
      @newpost = Post.create( title: params[:title], content: params[:blog], user_id: current_user.id)
  end

  def update
      @users = User.all
      @newpost = Post.create( title: params[:title], content: params[:blog], user_id: current_user.id)
      redirect_to '/users/:id'
  end

  def account
    @user = User.find_by(params[:session])
  end

  def new
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def posts
      @users = User.all
  end

  def create
      puts '**********************'
      puts params.inspect
      puts '**********************'
      # Find a user in the database that matches the username in the form.
      @user = User.find_by(username: params[:session][:username])
      p @user
      # Check if there is a user with that username, and check if the password is that user's password.
      if @user && @user.password == params[:session][:password]
          puts 'LOGIN SUCCESSFUL'
          log_in(@user)
          redirect_to user_path @user
      else
          puts 'LOGIN FAILED'
          redirect_to login_path
      end
  end

  def destroy
      log_out
      redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def current_user
    if session[:user_id]
        @current_user = User.find(session[:user_id])
    end
end

  def index
    @users = User.all
    @user = current_user
    @posts = Post.all
end

  def posts
    @users = User.all
    @user = current_user
    @posts = @user.posts
    @newpost = Post.create( title: params[:title], content: params[:blog], user_id: current_user.id)
  end

  def update
      @users = User.all
      @newpost = Post.create( title: params[:title], content: params[:blog], user_id: current_user.id)
      redirect_to '/posts'
  end

  def account
    @user = User.find(session[:user_id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to '/posts'
    else
      render 'new'
    end
  end

  def show
      @users = User.all
      @user = current_user
      # @posts = @user.posts
  end

  def home
      @user = User.find(params[:id])
  end

  def destroy
      User.delete(params[:id])
      redirect_to '/login'
  end

  private

  def user_params
      params.require(:user).permit(:username, :email, :password_confirmation, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>

  <p><%= comment.content %></p>

<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for Comment.new, :url => user_post_comments_path(@user, @post) do |f| %>
    <%= f.text_area :content %>
    <br><br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Born Royal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




    <header>
        <ul>
            <li>|</li>

          <% if current_user %>
                <li><a href="/" style= "color: #fcf3f4;" >Home</a></li>
                <li><a href="/posts" style= "color: #fcf3f4;" >My Posts</a></li>
                <li><a href="/users/:id" style= "color: #fcf3f4;" >Add a Post</a></li>
                <li><a href="/account" style= "color: #fcf3f4;" >Account</a></li>
          <% end %>

            <% if !current_user.nil? %>
              <%= link_to 'Log Out', logout_path, method: :delete %>
            <% else %>
              <%= link_to 'Log In', login_path %>
            <% end %>
            <li>|</li>
        </ul>

    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<!-- <h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p> -->
<div class="bodyContainer">

  <h1><%= @user.fname %>'s </em> Posts!</h1>

  <div class="userPost">
    <% @posts.each do |post| %>
          <div class="indiePost">
                <h3><%= link_to(post.title,user_post_path(@user,post)) %></a></h3>
          </p>


         </div>
        <br>
    <% end %>


  </div>

app/views/posts/new.html.erb
<!-- <h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p> -->

app/views/posts/show.html.erb
<!-- <h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p> -->


      <div class="indiePost">
          <h3><%= @post.title %></h3>
      </p>
        <p>
            <%= @post.content %>
        </p>

     </div>
    <br>

    <div id="comment">
        <h3>Comments</h3>
    </div>

     <div class="commentContent">
          <%= render 'comments/comment' %>
          <br>
     </div>

app/views/users/account.html.erb
<div class="bodyContainer">
  <div class="signUp">

    <h1>Edit Account:</h1>
    <!-- <p>Find me in app/views/users/new.html.erb</p> -->


    <%= form_for @user do |f| %>

        <div class="sign">
          <%= f.label :username, "Username: " %>
          <%= f.text_field :username %>
        </div>

        <div class="sign">
          <%= f.label :fname, "First Name: " %>
          <%= f.text_field :fname %>
        </div>

        <div class="sign">
          <%= f.label :lname, "Last Name: " %>
          <%= f.text_field :lname %>
        </div>

        <div class="sign">
          <%= f.label :email, "Email: " %>
          <%= f.text_field :email %>
        </div>

        <div class="sign">
          <%= f.label :password, "Password: " %>
          <%= f.password_field :password %>
        </div>

        <div class="sign">
          <%= f.label :password_confirmation, "Confirm Password: " %>
          <%= f.password_field :password_confirmation %>
        </div>

        <div class="sign">
          <%= f.submit "Save" %>
        </div>

    <% end %>




  </div>
</div>

app/views/users/index.html.erb
<!-- This is the homepage -->
<div class="bodyContainer">
  <h1><em>Bonjour!</em> </h1>
  <!-- <p>Find me in app/views/users/index.html.erb</p> -->


  <div class="userPost">
      <% @posts.each do |post| %>
            <h3><%= post.title %></h3>
          <p>
              <%= post.content %>
          </p>
          <br>
      <% end %>
  </div>

app/views/users/new.html.erb
<div class="bodyContainer">
  <div class="signUp">

    <% if @user.errors.full_messages %>
      <% @user.errors.full_messages.each do |message| %>
        <p style = "color:red"><strong> <%= message %> </strong></p>
      <% end %>
    <% end %>


    <h1>Sign Up:</h1>
    <!-- <p>Find me in app/views/users/new.html.erb</p> -->

    <%= form_for @user do |f| %>

      <div class="sign">
        <%= f.label :username, "Username: " %>
        <%= f.text_field :username %>
      </div>

      <div class="sign">
        <%= f.label :fname, "First Name: " %>
        <%= f.text_field :fname %>
      </div>

      <div class="sign">
        <%= f.label :lname, "Last Name: " %>
        <%= f.text_field :lname %>
      </div>

      <div class="sign">
        <%= f.label :email, "Email: " %>
        <%= f.text_field :email %>
      </div>

      <div class="sign">
        <%= f.label :password, "Password: " %>
        <%= f.password_field :password %>
      </div>

      <div class="sign">
        <%= f.label :password_confirmation, "Confirm Password: " %>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class="sign">
        <%= f.submit "Create Account" %>
      </div>

    <% end %>

  </div>
</div>

app/views/users/posts.html.erb
<!-- This is the posts page -->

<div class="bodyContainer">
    <h1><em>Posts!</em></h1>
</div>

<div class="body">
    <div class="sidebar">
        <h1>Check Out Some Other Posts!</h1>

          <div class="users">
            <% @users.each do |user| %>
            <br><br>
                <h2>
                    <%= link_to(user.username, user_posts_path(user) ) %>
                </h2>
                <p>
                    <a href="mailto:someone@example.com?Subject=Hello%20again"><%= user.email %></a>
                </p>

                <p>
                    created: <%= time_ago_in_words(user.created_at) %> ago
                </p>
            <% end %>

            </div>
          </div>


          <div class="userPost2">
            <% @posts.each do |post| %>
                  <h3><%= post.title %></h3>
                <p>
                    <%= post.content %>
                </p>
                <br>
            <% end %>

        </div>
    </div>

app/views/users/show.html.erb
<!-- <h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p> -->

<div class="bodyContainer">

  <h1><em>Bienvenue</em> <%= @user.fname %> </em>!</h1>


  <%= form_for @user do |f| %>

          <form class="" action='/users' method="post">
            <input id="titleForm" placeholder="Title" type="text" name="title" >
            <input id="contentForm" textarea name="blog" placeholder="Post" rows="8" cols="80"></textarea>
            <input id="editBtn" type='submit' name="" value="submit">
          </form>

    <% end %>


</div>




  <p>Click here to delete account:
      <%= link_to("Delete Account", user_path(@user), method: :delete) %>
  </p>